#216 Additional options for update/revert apply operations
wildfly-extras/prospero pull request #363
Opened 2023-04-13 11:45 UTC by parsharma

Issue: https://github.com/wildfly-extras/prospero/issues/216

2023-04-13 12:03 UTC, spyrkob requested changes
Thanks @parsharma looks good. A few comments below.

Could you also add unit tests for removing the candidate and a usage description for `--rm` in UsageMessages.properties please?

2023-04-13 12:03 UTC, spyrkob commented on prospero-cli/src/main/java/org/wildfly/prospero/cli/commands/UpdateCommand.java
> +        @CommandLine.Option(names = CliConstants.SKIP_CONFLICTS)
turns out this part is already implemented (as `yes` parameter). Sorry my mistake I forgot it was already done in a different issue. Could you remove the `skipConflicts` part please?

2023-04-14 07:16 UTC, parsharma commented
Thanks for the review comments. I have updated the code.

2023-04-14 09:07 UTC, spyrkob approved these changes
LGTM, thanks @parsharma

2023-06-07 09:05 UTC, spyrkob commented
@parsharma sorry, I'm holding on with merging this until we're ready to move to 1.1.x. I'll resolve the conflicts when it's ready

2023-09-12 10:24 UTC, spyrkob commented
Superseded by #456.

Thanks @parsharma I rebased your PR and will merge it in new PR. Sorry for delay!

2023-09-12 10:24 UTC, closed without merging