JBEAP-24602: handle badly formatted artifact cache
wildfly-extras/prospero pull request #540
Opened 2024-01-15 15:48 UTC by michpetrov

Issue: [JBEAP-26402](https://issues.redhat.com/browse/JBEAP-26402)

2024-01-17 09:20 UTC, spyrkob requested changes
Thanks @michpetrov. A couple of comments, plus could you port it to 1.1.x branch as well please?

2024-01-18 14:03 UTC, michpetrov commented on prospero-common/src/main/java/org/wildfly/prospero/galleon/ArtifactCache.java
> +                        throw new MavenUniverseException("Bad record format");
If I add this to the logger what about the IOE in the catch block? I'd assume we want the top message to be the same, i.e. "can't read cache".

2024-01-18 17:22 UTC, spyrkob commented on prospero-common/src/main/java/org/wildfly/prospero/galleon/ArtifactCache.java
> +                        throw new MavenUniverseException("Bad record format");
ah good point, I remember why it was using MavenUniverseException. It's the top level catch that should have a more descriptive error message

2024-01-19 12:12 UTC, michpetrov commented on prospero-common/src/main/java/org/wildfly/prospero/galleon/ArtifactCache.java
> +                        throw new MavenUniverseException("Bad record format");
@spyrkob well what messages do you want me to change then?

2024-01-19 14:39 UTC, spyrkob commented on prospero-common/src/main/java/org/wildfly/prospero/galleon/ArtifactCache.java
> +                        throw new MavenUniverseException("Bad record format");
@michpetrov the one in `throw new IOException("Unable to read cached items.", e);` if you don't mind adding this to this PR

2024-01-22 16:41 UTC, michpetrov commented
@spyrkob does this work? I'll port it to 1.1.x if there're no further requests.

2024-01-23 09:01 UTC, spyrkob approved these changes
Thanks @michpetrov that looks great!

2024-02-06 12:18 UTC, merged