channel list output is confusing #755
wildfly-extras/prospero pull request #777
Opened 2024-10-16 08:25 UTC by parsharma

Issue: https://github.com/wildfly-extras/prospero/issues/755

2024-10-16 16:08 UTC, spyrkob requested changes

2024-10-16 16:08 UTC, spyrkob commented on prospero-cli/src/main/java/org/wildfly/prospero/cli/commands/ChannelCommand.java
> +        @CommandLine.Option(names = CliConstants.FULL)
New options need to be described in the `UsageMessages.properties`

2024-10-16 16:08 UTC, spyrkob commented on prospero-cli/src/test/java/org/wildfly/prospero/cli/commands/ChannelCommandTest.java
> +        Assert.assertEquals(3, getStandardOutput().lines()
Use `Assertions.assertThat` and compare it to actual expected lines ("test1 g:a", "test2 g:a:v", "test3 file:/a:b")

2024-10-16 16:08 UTC, spyrkob commented on prospero-cli/src/test/java/org/wildfly/prospero/cli/commands/ChannelCommandTest.java
> +        Assert.assertTrue("Expected 'schemaVersion' in the output",
The test doesn't actually verify that the correct values are printed.  You should be able to get the output, convert it back to Channel objects and compare with the input. 
Or simply compare the output with serialized input.

2024-10-22 11:21 UTC, parsharma commented
@spyrkob, I have updated the code according to the review comments. Please have a look and let me know if more changes are needed.
Thanks

2024-10-23 09:57 UTC, merged